### PR TITLE
Restructure code and update coordinates

### PR DESCRIPTION
**Pull request by StevenJW**
Hi AmarSaini!

I've encountered your tracker and thought it was pretty cool. I did have to edit it somewhat because the cards are outdated since there have been added some new cards to Clash Royale. Also the spectate mode has been updated with a different view so I adjusted the card pixels for 1920x1080. I have not been able to get the elixer tracker working yet so I will be trying that out. 
Furthermore, I have split up your main file into a bunch of different files to make it easier to edit.

### CODE REVIEW

**Comment by AmarSaini** [comment]
Hey!

Wow this looks great! I've been meaning to jump back into this project for some time now. I'll check everything out soon :)

**Comment by StevenJW** [comment]
Thanks, I forgot to add that I've also added a dropout to the LeNet model because some images were not predicted right. I am actually not sure if it improved the model a lot so I probably should look into it more.

**Comment by AmarSaini** [comment]
Ah interesting! I was actually thinking of switching up the model architecture myself :P

**Comment by AmarSaini** [comment]
Hey sorry for taking so long to do the merge. Also was going to say, have much PyTorch experience? I'm thinking of maybe retraining/redesigning the Conv Nets in PyTorch.

**Pull request merged**
